spring.application.name=API-REST-GyselMood

server.port= 8080

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/db_catalogo_gym}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:mysql}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:imgapi}
cloudinary.api-key=${CLOUDINARY_API_KEY:256116538663764}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:9dfbMS5H1XssIc8plrjeUu8AySU}

jwt.secret=MiClaveSuperSecretaParaGymAda2026JwtSegura123456789
jwt.expiration=86400000

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.default-property-inclusion=non_null
spring.jackson.visibility.field=any

spring.jpa.open-in-view=false
